# .platform.app.yaml

# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: ozout

# The type of the application to build.
type: php:7.1
build:
  flavor: composer

# The configuration of app when it is exposed to the web.
web:
    # The public directory of the app, relative to its root.
    document_root: '/web'
    # The front-controller script to send non-static requests to.
    passthru: '/app.php'

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    '/var/cache': 'shared:pictures/cache'
    '/var/logs': 'shared:pictures/logs'
    '/var/sessions': 'shared:pictures/sessions'

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
      rm web/app_dev.php
    deploy: |
      bin/console --env=prod cache:clear