<?php

namespace AppBundle\Repository;

/**
 * categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoryRepository extends \Doctrine\ORM\EntityRepository
{
}
