<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEventByUserCreator(User $user){
        $qb = $this->createQueryBuilder('e');
        $qb->select('e')
            ->join('e.reservations', 'r')
            ->where('r.user = :user')
            ->andWhere('r.isCreator = true')
            ->setParameter('user', $user->getId());

        return $qb->getQuery()->getResult();
    }

    public function getEventByUserParticipate(User $user){
        $qb = $this->createQueryBuilder('e');
        $qb->select('e')
            ->join('e.reservations', 'r')
            ->where('r.user = :user')
            ->andWhere('r.isCreator = false')
            ->setParameter('user', $user->getId());

        return $qb->getQuery()->getResult();
    }
}
