<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function getAllNotPrivateEvent(){
        $qb = $this->createQueryBuilder('e');
        $qb->select('e')
            ->join('e.picture', 'p')
            ->addSelect('p')
            ->where('e.isPrivate = false')
            ->orderBy('e.start', 'ASC')
            ->setMaxResults(9);
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * @param \AppBundle\Entity\User $user
     *
     * @return mixed
     */
    public function getEventByUserCreator(User $user){
        $qb = $this->createQueryBuilder('e');
        $qb->select('e')
            ->join('e.reservations', 'r')
            ->where('r.user = :user')
            ->andWhere('r.isCreator = true')
            ->setParameter('user', $user->getId())
            ->orderBy('e.start', 'ASC')
        ;

        return $qb->getQuery()->getResult();
    }

    public function getEventByUserParticipate(User $user){
        $qb = $this->createQueryBuilder('e');
        $qb->select('e')
            ->join('e.reservations', 'r')
            ->where('r.user = :user')
            ->andWhere('r.isCreator = false')
            ->setParameter('user', $user->getId());

        return $qb->getQuery()->getResult();
    }
}
