<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIdEventReservationByUser($user){
        $qb = $this->createQueryBuilder('r');
        $qb->join('r.event', 'e')
            ->select('e.id')
            ->where('r.user = :user')
            ->setParameter('user', $user->getId())
        ;
        return $qb->getQuery()->getResult();
    }
}
